=== bajra-manandhar17/xml/Week 18/employees2.dtd
<!ELEMENT employees2 (employee+)>
<!ELEMENT employee (name,department,address?,phone*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>

=== bajra-manandhar17/xml/Week 18/employees2.xml
<!DOCTYPE employees2 SYSTEM "employees2.dtd">

<employees2>
   <employee>
      <name>Bajra Manandhar</name>
      <department>IT Department</department>
      <address>Ghar</address>
   </employee>

   <employee>
      <name>Shubigyan Adhikari</name>
      <department>Business Department</department>
      <phone>1234567</phone>
      <phone>67888956</phone>
   </employee>
</employees2>
