<!DOCTYPE employees [
   <!ELEMENT employees (employee+)>
   <!ELEMENT employee (name,department,address?,phone*)>
   <!ATTLIST employee employeeType CDATA #IMPLIED>
   <!-- <!ATTLIST employee employeeType (PartTime|FullTime) #REQUIRED> -->
   <!-- <!ATTLIST employee employeeType CDATA #REQUIRED> -->
   <!-- <!ATTLIST employee employeeType CDATA "Full Time"> -->
   <!ELEMENT name (#PCDATA)>
   <!ELEMENT department (#PCDATA)>
   <!ELEMENT address (#PCDATA)>
   <!ELEMENT phone (#PCDATA)>
   <!ENTITY loc "Kathmandu, Nepal">
   <!-- Parameter Entity Reference: Combining Two Files
   <!ENTITY %employee SYSTEM "employees.dtd"> 
   <!ENTITY %rest SYSTEM "rest.dtd">
   %employee; 
   %rest;-->
]>

<employees>
   <employee employeeType="Part Time">
      <name>Bajra Manandhar</name>
      <department>IT Department</department>
      <address>Ghar &loc;</address>
   </employee>

   <employee employeeType="Part Time">
      <name>FirstName LastName</name>
      <department>Finance Department</department>
      <address>Kamalpokhari</address>
   </employee>

   <employee>
      <name>Shubigyan Adhikari</name>
      <department>Business Department</department>
      <phone>1234567</phone>
      <phone>67888956</phone>
   </employee>
</employees>
